### ISSUE TITLE
How to execute using Docker

### ISSUE THREAD

**Issue by MahajanTarun** [difi/Oxalis-AS4#103]
Hi @FrodeBjerkholt. I am completely new to Oxalis-as4 but for a project, I want to run using docker.

I tried running the docker as per the instructions in this link: https://hub.docker.com/r/digdir/oxalis-as4
All the required files as in the instructions were placed in the destination folder
But I am unable to run it. 
Please guide me through it on how to run using docker file.

**Comment by FrodeBjerkholt** [comment]
Perhaps you can try docker-compose? You can try with a docker-compose.yml like this:

```yml
version: '3.3'
services:

  oxalis-as4:
    image: "digdir/oxalis-as4:4.1.6" 
    environment:
      OXALIS_HOME: /etc/oxalis
    volumes:
        - ./peppoltest/.oxalis:/etc/oxalis
        - ./peppoltest/peppol:/var/peppol/
    ports:
      - 8080:8080
```
